spring:
  application:
    name: file-manager
    file:
      storage:
        technology: ftp
        ftp:
          server: localhost
          port: 21
          username: user
          password: password
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fileManager?useSSL=false&allowPublicKeyRetrieval=True&createDatabaseIfNotExist=true
    username: root
    password=: root