spring:
  application:
    name: file-manager
    file:
      storage:
        technology: ftp
        ftp:
          server: localhost
          port: 21
          username: user
          password: password
        s3:
          server: http://localhost:4566/
          access-key-id: test
          secret-key: test
          region: us-east-1
          bucket-name: file-manager-bucket #same name as the BUCKET_NAME on docker/create_bucket.sh
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fileManager?useSSL=false&allowPublicKeyRetrieval=True&createDatabaseIfNotExist=true
    username: root
    password=: root